name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'gradle'
        
    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1
      
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Clean and assemble
      run: |
        ./gradlew clean
        ./gradlew assembleDebug --stacktrace --no-daemon
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: SaltPlayerRemote-APK
        path: app/build/outputs/apk/debug/app-debug.apk
